# Justs repackages the Spread binaries.
# Puts binaries into build/bin.

# See README.txt for system requirements.

# See spread.mk for the input files required in tmp/.

default: install_spread

build: build_spread

install: install_spread

include mk/common.mk
include mk/spread.mk
