minimum_pre_commit_version: '3.6'
repos:
  - repo: https://github.com/pycqa/isort
    rev: "5.13.2"
    hooks:
    - id: isort
  - repo: https://github.com/hhatto/autopep8
    rev: "v2.3.1"
    hooks:
    - id: autopep8
      args: [--in-place, --aggressive, --aggressive]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    - id: pyupgrade
      args: [--py38-plus]
  - repo: https://github.com/PyCQA/flake8
    rev: "6.1.0"
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-coding == 1.3.2
        - flake8-debugger == 4.1.2
