repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.6.2
    hooks:
    - id: pyupgrade
      args: [--py36-plus]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: debug-statements
