# Makefile.nt

VERSION = 2.0a4
CC = cl
CFLAGS = /W3 /DWIN32 /I..
LIBS = wsock32.lib
SRCDIR= ..
CREOSOTE_DIR = $(SRCDIR)/MrCreosote
CORE = $(SRCDIR)/pcgi.h #parseinfo.c

.c.obj:
	$(CC) /c $(CFLAGS) $*.c

all:	pcgi-wrapper.exe parseinfo.exe creosote.obj

creosote.obj:	$(CREOSOTE_DIR)/creosote.c $(CREOSOTE_DIR)/creosote.h
	$(CC) /c $(CFLAGS) /I$(CREOSOTE_DIR) /Focreosote.obj $(CREOSOTE_DIR)/creosote.c

parseinfo1.obj:	$(SRCDIR)/parseinfo.c $(CORE)
	$(CC) /c $(CFLAGS) /DMAIN_PARSEINFO /Foparseinfo1.obj $(SRCDIR)/parseinfo.c 

parseinfo2.obj:	$(SRCDIR)/parseinfo.c $(CORE)
	$(CC) /c $(CFLAGS) $(SRCDIR)/parseinfo.c /Foparseinfo2.obj

pcgi-wrapper1.obj: $(SRCDIR)/pcgi-wrapper.c $(CORE)
	$(CC) /c $(CFLAGS) /I$(CREOSOTE_DIR) /DPCGI_WRAPPER_MAIN /DCREOSOTE /DVERSION=\"$(VERSION)\" /Fopcgi-wrapper1.obj $(SRCDIR)/pcgi-wrapper.c

pcgi-wrapper2.obj: $(SRCDIR)/pcgi-wrapper.c $(CORE)
	$(CC) /c $(CFLAGS) /I$(CREOSOTE_DIR) /DCREOSOTE /Fopcgi-wrapper2.obj $(SRCDIR)/pcgi-wrapper.c

parseinfo.exe:	parseinfo1.obj pcgi-wrapper2.obj creosote.obj
	link /OUT:parseinfo.exe parseinfo1.obj pcgi-wrapper2.obj creosote.obj $(LIBS)

pcgi-wrapper.exe: pcgi-wrapper1.obj parseinfo2.obj creosote.obj
	link /OUT:pcgi-wrapper.exe pcgi-wrapper1.obj parseinfo2.obj creosote.obj $(LIBS)
